- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    dest_key_pub: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"

  tasks:
    - name: Install git
      community.general.homebrew:
        name: git
        state: present
      become: false
    - name: Install tmux
      community.general.homebrew:
        name: tmux
        state: present
      become: false
    - name: Install Neovim
      community.general.homebrew:
        name: neovim
        state: present
      become: false
    - name: Install fzf
      community.general.homebrew:
        name: fzf
        state: present
      become: false
    - name: Ensure the SSH directory exists
      ansible.builtin.file:
        path: "~/.ssh"
        state: directory
        mode: '0700'
    - name: Decrypt and copy the SSH private key
      ansible.builtin.copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: '0600'
        decrypt: yes
      become: false
    - name: Copy the SSH public key
      ansible.builtin.copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: '0600'
      become: false
    - name: Set authorized key took from file
      authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        state: present
        key: "{{ lookup('file', dest_key_pub) }}"
        manage_dir: yes
    - name: Check if Oh My Zsh is installed
      ansible.builtin.stat:
        path: ~/.oh-my-zsh
      register: oh_my_zsh
    - name: Install Oh My Zsh
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
      when: not oh_my_zsh.stat.exists
    - name: Clone dotfiles
      git:
        repo: 'git@github.com:ashinmk/dotfiles.git'
        dest:  "{{ lookup('env', 'HOME') }}/dotfiles"
        version: 'ashin-test'  # or any branch/tag/commit
        #key_file: /Users/ec2-user/.ssh/id_rsa
    - name: Install dotfiles
      shell: zsh "{{ lookup('env', 'HOME') }}/dotfiles/install.sh"
      args:
        chdir: "{{ lookup('env', 'HOME') }}/dotfiles"
